import { EquipmentSlot, system, world } from "@minecraft/server";
import { ACTIVITY_DELAY } from "./config.js";
import { getBlueprint } from "./blueprints.js";
import { ensureHome, isBuilding } from "./building.js";
import { isTunneling } from "./tunnel.js";
import { isRepairing } from "./maintenance.js";
import { cancelMovement, goTo } from "./movement.js";
import { setRuntime, state } from "./storage.js";
import { blockAt, distance, equip, getSurface, isReplaceableType, isValid, lookAt, nearestPlayer, normalize2D, play, pointRelativeToPlayer, randomBetween, safePlace, smoke, sound } from "./utils.js";
import { error } from "./logger.js";
const controllers=new Map();
function runtime(entity){let value=controllers.get(entity.id);if(!value){value={busy:false,timer:undefined,last:"",started:0,generation:0};controllers.set(entity.id,value);}return value;}
function absolute(origin,offset){return{x:origin.x+offset.x,y:origin.y+offset.y,z:origin.z+offset.z};}
function delayForActivity(){const range=ACTIVITY_DELAY[state().settings.activity]??ACTIVITY_DELAY.normal;return Math.floor(randomBetween(range[0],range[1]));}
function active(entity,token){const value=runtime(entity);return isValid(entity)&&value.busy&&value.generation===token;}
function wait(entity,token,ticks){return new Promise(resolve=>system.runTimeout(()=>resolve(active(entity,token)),Math.max(1,ticks)));}
function armTimer(entity,delay){const value=runtime(entity);if(value.timer!==undefined)system.clearRun(value.timer);if(!state().settings.autonomous){value.timer=undefined;return;}value.timer=system.runTimeout(()=>{value.timer=undefined;chooseAction(entity);},delay);}
function begin(entity,name){const value=runtime(entity);value.generation++;value.busy=true;value.started=system.currentTick;value.last=name;setRuntime({currentAction:name,actionStartedTick:system.currentTick,lastError:""});return value.generation;}
function finish(entity,name,token){if(!isValid(entity))return;const value=runtime(entity);if(value.generation!==token)return;value.busy=false;value.started=0;value.last=name;equip(entity,undefined);try{entity.isSneaking=false;}catch{}try{entity.triggerEvent("hiw:set_idle");}catch{}setRuntime({currentAction:"idle",lastAction:name,actionStartedTick:0});armTimer(entity,delayForActivity());}
async function move(entity,token,target,options={}){if(!active(entity,token))return false;const result=await goTo(entity,target,options);return active(entity,token)&&result.success;}
async function homeRoutine(entity,token){const home=state().home;if(!home.origin)return finish(entity,"home",token);const blueprint=getBlueprint(home.variant);const player=nearestPlayer(entity);for(const station of blueprint.stations){if(!active(entity,token))return;equip(entity,station.item);const target=absolute(home.origin,station.offset);if(!await move(entity,token,target,{speed:"walk",arrivalRadius:1.9}))break;if(player&&station.name==="wejscie")lookAt(entity,player.location);play(entity,station.animation);if(!await wait(entity,token,station.wait))return;}finish(entity,"home",token);}
async function patrol(entity,token){const home=state().home;if(!home.origin)return finish(entity,"patrol",token);const player=nearestPlayer(entity);for(let i=0;i<4;i++){if(!active(entity,token))return;const angle=Math.random()*Math.PI*2;const radius=randomBetween(8,15);const surface=getSurface(entity.dimension,home.origin.x+Math.cos(angle)*radius,home.origin.z+Math.sin(angle)*radius);if(!surface)continue;const target={x:surface.location.x+0.5,y:surface.location.y+1,z:surface.location.z+0.5};if(!await move(entity,token,target,{speed:"auto"}))break;if(player&&Math.random()<0.55){lookAt(entity,player.location);play(entity,"animation.hiw.herobrine.stare");}if(!await wait(entity,token,28))return;}finish(entity,"patrol",token);}
async function guardHome(entity,token){const home=state().home;if(!home.origin)return finish(entity,"guard",token);const blueprint=getBlueprint(home.variant);const r=blueprint.radius+3;const points=[{x:home.origin.x,y:home.origin.y,z:home.origin.z-r},{x:home.origin.x+r,y:home.origin.y,z:home.origin.z},{x:home.origin.x,y:home.origin.y,z:home.origin.z+r},{x:home.origin.x-r,y:home.origin.y,z:home.origin.z}];equip(entity,"minecraft:iron_sword");for(let loop=0;loop<2;loop++)for(const point of points){if(!active(entity,token))return;if(!await move(entity,token,point,{speed:"walk",arrivalRadius:2.1}))break;const player=nearestPlayer(entity,28);if(player)lookAt(entity,player.location);play(entity,"animation.hiw.herobrine.stare");if(!await wait(entity,token,22))return;}finish(entity,"guard",token);}
async function approachPlayer(entity,token){const player=nearestPlayer(entity);if(!player)return finish(entity,"come",token);const view=normalize2D(player.getViewDirection());const target={x:player.location.x-view.x*3.5,y:player.location.y,z:player.location.z-view.z*3.5};equip(entity,undefined);const success=await move(entity,token,target,{speed:"auto",arrivalRadius:2.2});if(success){lookAt(entity,player.location);play(entity,"animation.hiw.herobrine.stare");await wait(entity,token,45);}finish(entity,"come",token);}
async function followPlayer(entity,token){const player=nearestPlayer(entity);if(!player)return finish(entity,"follow",token);equip(entity,Math.random()<0.25?"minecraft:iron_sword":undefined);const endTick=system.currentTick+20*35;while(active(entity,token)&&isValid(player)&&system.currentTick<endTick){const view=normalize2D(player.getViewDirection());const target={x:player.location.x-view.x*5.5,y:player.location.y,z:player.location.z-view.z*5.5};const currentDistance=distance(entity.location,player.location);if(currentDistance>7.5)await move(entity,token,target,{speed:currentDistance>16?"sprint":"walk",arrivalRadius:2.4,segmentTimeoutTicks:20*8});else{lookAt(entity,player.location);if(!await wait(entity,token,20))return;}}finish(entity,"follow",token);}
async function waitHere(entity,token){try{entity.triggerEvent("hiw:set_freeze");}catch{}play(entity,"animation.hiw.herobrine.stare");const end=system.currentTick+20*60;while(active(entity,token)&&system.currentTick<end){const player=nearestPlayer(entity,32);if(player)lookAt(entity,player.location);if(!await wait(entity,token,20))return;}finish(entity,"wait",token);}
async function observe(entity,token){const player=nearestPlayer(entity);if(!player)return finish(entity,"observe",token);const point=pointRelativeToPlayer(player,-16,Math.random()<0.5?-6:6);const surface=getSurface(player.dimension,point.x,point.z);if(!surface)return finish(entity,"observe",token);equip(entity,Math.random()<0.35?"minecraft:iron_sword":undefined);const target={x:surface.location.x+0.5,y:surface.location.y+1,z:surface.location.z+0.5};if(await move(entity,token,target,{speed:"auto"})){try{entity.triggerEvent("hiw:set_freeze");}catch{}play(entity,"animation.hiw.herobrine.stare");let waited=0;while(active(entity,token)&&waited<140){lookAt(entity,player.location);if(distance(entity.location,player.location)<5){smoke(entity.dimension,entity.location);sound(entity.dimension,"ambient.cave",entity.location,0.5,0.8);try{entity.addEffect("invisibility",40,{showParticles:false});}catch{}break;}waited+=10;if(!await wait(entity,token,10))return;}try{entity.removeEffect("invisibility");}catch{}}finish(entity,"observe",token);}
async function mimic(entity,token){const player=nearestPlayer(entity);if(!player)return finish(entity,"mimic",token);try{const held=player.getComponent("minecraft:equippable")?.getEquipment(EquipmentSlot.Mainhand);const equipment=entity.getComponent("minecraft:equippable");if(held&&equipment)equipment.setEquipment(EquipmentSlot.Mainhand,held.clone());}catch{}const until=system.currentTick+20*10;while(active(entity,token)&&isValid(player)&&system.currentTick<until){try{entity.isSneaking=player.isSneaking;}catch{}const direction=player.getViewDirection();lookAt(entity,{x:entity.location.x+direction.x*10,y:entity.location.y+1+direction.y*10,z:entity.location.z+direction.z*10});if(system.currentTick%40<10)play(entity,"animation.hiw.herobrine.attack");if(!await wait(entity,token,10))return;}finish(entity,"mimic",token);}
async function warning(entity,token){const player=nearestPlayer(entity);if(!player||!state().settings.interferenceEnabled)return finish(entity,"warning",token);const angle=Math.random()*Math.PI*2;const surface=getSurface(player.dimension,player.location.x+Math.cos(angle)*5,player.location.z+Math.sin(angle)*5);if(!surface)return finish(entity,"warning",token);const target={x:surface.location.x,y:surface.location.y+1,z:surface.location.z};if(!isReplaceableType(blockAt(player.dimension,target)?.typeId))return finish(entity,"warning",token);equip(entity,"minecraft:redstone_torch");if(await move(entity,token,{x:target.x+0.5,y:target.y,z:target.z+0.5},{speed:"walk",arrivalRadius:2.0})){play(entity,"animation.hiw.herobrine.attack");if(!await wait(entity,token,6))return;safePlace(player.dimension,target,"minecraft:redstone_torch",true);sound(player.dimension,"ambient.cave",target,0.55,0.7);}finish(entity,"warning",token);}
function findTree(entity,radius=15){const baseY=Math.floor(entity.location.y);for(let r=3;r<=radius;r++)for(let i=0;i<20;i++){const angle=Math.PI*2*i/20;const x=Math.floor(entity.location.x+Math.cos(angle)*r);const z=Math.floor(entity.location.z+Math.sin(angle)*r);for(let y=baseY-5;y<=baseY+9;y++){const block=blockAt(entity.dimension,{x,y,z});if(!block?.typeId?.includes("_log"))continue;const below=blockAt(entity.dimension,{x,y:y-1,z});if(below?.typeId===block.typeId)continue;return block;}}}
function saplingFor(logId){const map={"minecraft:mangrove_log":"minecraft:mangrove_propagule","minecraft:crimson_stem":"minecraft:crimson_fungus","minecraft:warped_stem":"minecraft:warped_fungus"};return map[logId]??logId.replace("_log","_sapling");}
async function chop(entity,token){const tree=findTree(entity);if(!tree)return finish(entity,"chop",token);equip(entity,"minecraft:iron_axe");const surface=getSurface(entity.dimension,tree.location.x+1,tree.location.z);const target=surface?{x:surface.location.x+0.5,y:surface.location.y+1,z:surface.location.z+0.5}:{x:tree.location.x+1.5,y:tree.location.y,z:tree.location.z+0.5};if(await move(entity,token,target,{speed:"walk",arrivalRadius:2.0})){for(let i=0;i<3;i++){play(entity,"animation.hiw.herobrine.attack");sound(entity.dimension,"dig.wood",tree.location,0.9,0.5);if(!await wait(entity,token,8))return;}if(!state().settings.safeMode){const logType=tree.typeId;for(let dy=0;dy<6;dy++){if(!active(entity,token))return;const block=blockAt(entity.dimension,{x:tree.location.x,y:tree.location.y+dy,z:tree.location.z});if(block?.typeId!==logType)break;try{entity.dimension.setBlockType(block.location,"minecraft:air");}catch{}if(!await wait(entity,token,5))return;}safePlace(entity.dimension,tree.location,saplingFor(logType),true);}}finish(entity,"chop",token);}
async function darkHome(entity,token){const home=state().home;if(!home.origin)return finish(entity,"dark_home",token);const target={x:home.origin.x+0.5,y:home.origin.y+1,z:home.origin.z+0.5};if(await move(entity,token,target,{speed:"walk",arrivalRadius:1.7})){try{entity.triggerEvent("hiw:set_freeze");}catch{}play(entity,"animation.hiw.herobrine.stare");await wait(entity,token,160);}finish(entity,"dark_home",token);}
function weightedChoice(entries){const last=state().runtime.lastAction;const filtered=entries.filter(([name])=>name!==last);const values=filtered.length?filtered:entries;let roll=Math.random()*values.reduce((sum,item)=>sum+item[1],0);for(const item of values){roll-=item[1];if(roll<=0)return item[0];}return values[0][0];}
const ACTIONS={home:homeRoutine,patrol,guard:guardHome,come:approachPlayer,follow:followPlayer,wait:waitHere,observe,mimic,warning,chop,dark_home:darkHome};
export function chooseAction(entity){if(!isValid(entity)||isBuilding(entity)||isTunneling(entity)||isRepairing(entity))return;const value=runtime(entity);if(value.busy||!state().settings.autonomous)return;if(state().home.status==="paused"){setRuntime({currentAction:"build_paused",actionStartedTick:0});return;}if(state().home.status!=="complete"){ensureHome(entity,nearestPlayer(entity),()=>scheduleNext(entity,20));return;}const night=(()=>{try{const time=world.getTimeOfDay();return time>12500&&time<23500;}catch{return false;}})();const selected=weightedChoice([["home",night?18:10],["patrol",11],["guard",7],["observe",14],["mimic",7],["warning",6],["chop",5],["dark_home",night?11:2]]);const token=begin(entity,selected);Promise.resolve(ACTIONS[selected](entity,token)).catch(e=>{error(`action-${selected}`,e);finish(entity,selected,token);});}
export function scheduleNext(entity,delay){if(!isValid(entity))return;const value=runtime(entity);value.busy=false;armTimer(entity,delay??delayForActivity());}
export function startController(entity){if(!isValid(entity))return;const value=runtime(entity);if(value.timer!==undefined||value.busy)return;if(state().home.status==="paused"){setRuntime({currentAction:"build_paused",actionStartedTick:0});return;}if(!state().settings.autonomous&&state().home.status==="complete"){setRuntime({currentAction:"idle",actionStartedTick:0});return;}ensureHome(entity,nearestPlayer(entity),()=>scheduleNext(entity,40));}
export function recoverController(entity){if(!isValid(entity)||isBuilding(entity)||isTunneling(entity)||isRepairing(entity))return;const value=runtime(entity);if(value.busy&&system.currentTick-value.started>1900){stopController(entity,"watchdog");setRuntime({currentAction:"idle",actionStartedTick:0,lastError:"Watchdog anulowal zawieszona akcje."});scheduleNext(entity,40);}else if(!value.busy&&value.timer===undefined&&state().settings.autonomous)startController(entity);}
export function stopController(entity,reason="manual_stop"){if(!isValid(entity))return;const value=runtime(entity);value.generation++;if(value.timer!==undefined){system.clearRun(value.timer);value.timer=undefined;}cancelMovement(entity,reason);value.busy=false;value.started=0;try{entity.removeEffect("invisibility");}catch{}try{entity.isSneaking=false;}catch{}try{entity.triggerEvent("hiw:set_idle");}catch{}equip(entity,undefined);setRuntime({currentAction:"idle",actionStartedTick:0,lastError:""});}
export function commandAction(entity,name){if(!isValid(entity))return{success:false,reason:"Herobrine nie istnieje."};if(isBuilding(entity))return{success:false,reason:"Herobrine teraz buduje dom."};if(isTunneling(entity))return{success:false,reason:"Herobrine teraz kopie tunel."};if(isRepairing(entity))return{success:false,reason:"Herobrine teraz naprawia dom."};const action=ACTIONS[name];if(!action)return{success:false,reason:`Nieznane polecenie ${name}.`};stopController(entity,`command_${name}`);const token=begin(entity,name);Promise.resolve(action(entity,token)).catch(e=>{error(`command-${name}`,e);finish(entity,name,token);});return{success:true,reason:""};}
export function controllerStatus(entity){return entity?controllers.get(entity.id):undefined;}
