import { system } from "@minecraft/server";
import { BUILD } from "./config.js";
import { getBlueprint } from "./blueprints.js";
import { findBuildingSite, findSiteInFront } from "./site.js";
import { cancelMovement, goTo } from "./movement.js";
import { recordError, resetHome, setHome, setRuntime, state } from "./storage.js";
import { blockAt, distance, equip, isProtectedType, isReplaceableType, isValid, lookAt, play, sound } from "./utils.js";
import { entityInsideBlocks, healWorker, setWorkerMode, teleportWorkerSafely } from "./worker_safety.js";
import { error, info } from "./logger.js";
function currentBuildDelay(){const pace=state().settings.buildPace??"normal";return BUILD.paceTicks[pace]??BUILD.paceTicks.normal;}
let active;let generation=0;let searchActive=false;
function absolute(origin,offset){return{x:origin.x+offset.x,y:origin.y+offset.y,z:origin.z+offset.z};}
function coordinateKey(location){return`${Math.floor(location.x)},${Math.floor(location.y)},${Math.floor(location.z)}`;}
function sortedBlocks(blueprint){return[...blueprint.blocks].sort((a,b)=>a.phase-b.phase||String(a.zone).localeCompare(String(b.zone))||a.offset.y-b.offset.y||a.offset.z-b.offset.z||a.offset.x-b.offset.x);}
function directSet(dimension,location,typeId){try{dimension.setBlockType({x:Math.floor(location.x),y:Math.floor(location.y),z:Math.floor(location.z)},typeId);return true;}catch{return false;}}
function naturalObstacle(typeId){return Boolean(typeId&&(typeId.includes("leaves")||typeId.includes("_log")||typeId.includes("_wood")||typeId.includes("_stem")||typeId.includes("dirt")||typeId.includes("grass_block")||typeId.includes("stone")||typeId.includes("deepslate")||typeId.includes("sand")||typeId.includes("gravel")||typeId.includes("snow")));}
function stationForZone(origin,zone,blueprint){const r=blueprint.radius+3;const values={north:{x:origin.x+0.5,y:origin.y,z:origin.z-r},entrance:{x:origin.x+0.5,y:origin.y,z:origin.z-r},south:{x:origin.x+0.5,y:origin.y,z:origin.z+r},west:{x:origin.x-r,y:origin.y,z:origin.z+0.5},east:{x:origin.x+r,y:origin.y,z:origin.z+0.5},roof:{x:origin.x+r,y:origin.y,z:origin.z-r},inside:{x:origin.x+0.5,y:origin.y,z:origin.z-r},floor:{x:origin.x+0.5,y:origin.y,z:origin.z-r},foundation:{x:origin.x+0.5,y:origin.y,z:origin.z-r}};if(values[zone])return values[zone];const parts=String(zone).split(":").map(Number);if(parts.length===2&&parts.every(Number.isFinite)){const[x,z]=parts;if(Math.abs(x)>=Math.abs(z))return x>=0?values.east:values.west;return z>=0?values.south:values.north;}return values.north;}
function expectedBlocks(blueprint,origin){const map=new Map();for(const entry of blueprint.blocks)map.set(coordinateKey(absolute(origin,entry.offset)),entry.typeId);return map;}
function clearTimer(session){if(session?.timer!==undefined){try{system.clearRun(session.timer);}catch{}session.timer=undefined;}}
function schedule(session,delay,callback){if(!session||active!==session)return;clearTimer(session);session.timer=system.runTimeout(()=>{session.timer=undefined;if(active!==session||session.token!==generation)return;callback();},Math.max(1,delay));}
function finishSession(entity){if(active?.entityId===entity?.id){clearTimer(active);active=undefined;}cancelMovement(entity,"building_finished");equip(entity,undefined);}
function pauseBuild(session,message){if(!session)return;finishSession(session.entity);try{session.entity.triggerEvent("hiw:set_idle");}catch{}setHome({status:"paused",pauseReason:message});setRuntime({currentAction:"build_paused",actionStartedTick:0,lastError:message});recordError(message);try{session.player?.sendMessage(`§c[Herobrine] Budowa zatrzymana: ${message}`);session.player?.sendMessage("§7Po usunieciu przeszkody wybierz w ksiazce Wznow budowe domu.");}catch{}}
function workerTooCloseToTarget(entity,target){return isValid(entity)&&distance(entity.location,target)<1.8&&Math.abs(entity.location.y-target.y)<2.2;}
function rescueToCurrentStation(session){if(!session||!isValid(session.entity))return false;const station=session.station??stationForZone(session.home.origin,"north",session.blueprint);const rescued=teleportWorkerSafely(session.entity,station,session.home.origin);if(rescued)setWorkerMode(session.entity);return rescued;}
async function moveToStation(session,zone,callback){if(!session||active!==session||!isValid(session.entity))return;const desired=stationForZone(session.home.origin,zone,session.blueprint);session.station=desired;session.zone=zone;cancelMovement(session.entity,"new_build_station");try{session.entity.triggerEvent("hiw:set_move");}catch{}let result;try{result=await goTo(session.entity,desired,{arrivalRadius:2.0,timeoutTicks:BUILD.stationTimeoutTicks,retries:0});}catch{result={success:false,reason:"movement_error"};}if(active!==session||session.token!==generation)return;if(!result?.success&&!teleportWorkerSafely(session.entity,desired,session.home.origin)){pauseBuild(session,`Nie znaleziono bezpiecznego punktu pracy (${result?.reason??"blad"}).`);return;}setWorkerMode(session.entity);healWorker(session.entity);callback();}
function prepareOneColumn(session){if(!session||active!==session||!isValid(session.entity))return;if(session.prepareIndex>=session.prepareColumns.length){setHome({prepared:true,status:"building",pauseReason:""});session.home.prepared=true;session.stage="blocks";session.lastZone="";startNextBlock(session);return;}const column=session.prepareColumns[session.prepareIndex++];const{origin}=session.home;const{blueprint,expected}=session;const dimension=session.entity.dimension;try{const worldX=origin.x+column.x,worldZ=origin.z+column.z;for(let y=origin.y-4;y<=origin.y-1;y++){const location={x:worldX,y,z:worldZ};const block=blockAt(dimension,location);if(!block)throw new Error("Chunk terenu zostal odladowany.");const expectedType=expected.get(coordinateKey(location));if(expectedType&&block.typeId===expectedType)continue;if(isProtectedType(block.typeId))throw new Error(`Chroniony blok ${block.typeId} pod miejscem budowy.`);if(isReplaceableType(block.typeId))directSet(dimension,location,y===origin.y-1?"minecraft:dirt":"minecraft:stone");}for(let y=origin.y;y<=origin.y+blueprint.height+2;y++){const location={x:worldX,y,z:worldZ};const block=blockAt(dimension,location);if(!block)throw new Error("Chunk domu zostal odladowany.");const expectedType=expected.get(coordinateKey(location));if(expectedType&&block.typeId===expectedType)continue;if(isProtectedType(block.typeId))throw new Error(`Chroniony blok ${block.typeId} przy ${worldX} ${y} ${worldZ}.`);if(block.typeId!=="minecraft:air"&&(isReplaceableType(block.typeId)||naturalObstacle(block.typeId)))directSet(dimension,location,"minecraft:air");}const support={x:worldX,y:origin.y-1,z:worldZ};const supportBlock=blockAt(dimension,support);const expectedSupport=expected.get(coordinateKey(support));if(supportBlock&&!(expectedSupport&&supportBlock.typeId===expectedSupport)){if(isProtectedType(supportBlock.typeId))throw new Error(`Chroniony fundament ${supportBlock.typeId}.`);directSet(dimension,support,"minecraft:dirt");}healWorker(session.entity);if(entityInsideBlocks(session.entity))rescueToCurrentStation(session);if(session.player&&session.prepareIndex%15===0)session.player.onScreenDisplay.setActionBar(`§8Przygotowanie terenu: ${session.prepareIndex}/${session.prepareColumns.length}`);schedule(session,BUILD.preparationColumnDelayTicks,()=>prepareOneColumn(session));}catch(e){error("build-prepare",e);pauseBuild(session,e instanceof Error?e.message:String(e));}}
function placeCurrentBlock(session){if(!session||active!==session||!isValid(session.entity))return;if(session.index>=session.blocks.length){completeBuild(session);return;}const entry=session.blocks[session.index];const target=absolute(session.home.origin,entry.offset);try{healWorker(session.entity);if(entityInsideBlocks(session.entity)||workerTooCloseToTarget(session.entity,target)){if(!rescueToCurrentStation(session))throw new Error("Nie udalo sie odsunac Herobrine'a od stawianego bloku.");}const existing=blockAt(session.entity.dimension,target);if(!existing)throw new Error("Chunk domu nie jest zaladowany.");if(existing.typeId===entry.typeId){session.index++;if(session.index%BUILD.saveEveryBlocks===0)setHome({buildIndex:session.index});schedule(session,1,()=>startNextBlock(session));return;}if(isProtectedType(existing.typeId))throw new Error(`Chroniony blok ${existing.typeId} przy ${target.x} ${target.y} ${target.z}.`);setWorkerMode(session.entity);lookAt(session.entity,{x:target.x+0.5,y:target.y+0.5,z:target.z+0.5});play(session.entity,"animation.hiw.herobrine.attack");if(!directSet(session.entity.dimension,target,entry.typeId))throw new Error(`Nie udalo sie postawic ${entry.typeId}.`);sound(session.entity.dimension,entry.sound,target,0.82,0.45);session.index++;if(session.index%BUILD.saveEveryBlocks===0)setHome({buildIndex:session.index});if(session.player)session.player.onScreenDisplay.setActionBar(`§8Budowa domu: ${session.index}/${session.blocks.length}`);schedule(session,currentBuildDelay(),()=>startNextBlock(session));}catch(e){error("build-place",e);pauseBuild(session,e instanceof Error?e.message:String(e));}}
function startNextBlock(session){if(!session||active!==session||!isValid(session.entity))return;if(session.index>=session.blocks.length){completeBuild(session);return;}const entry=session.blocks[session.index];const nextZone=String(entry.zone??"north");if(nextZone!==session.lastZone){session.lastZone=nextZone;moveToStation(session,nextZone,()=>{if(active===session)placeCurrentBlock(session);});return;}placeCurrentBlock(session);}
function completeBuild(session){if(!session||active!==session)return;const{entity,player,home,blocks}=session;finishSession(entity);setHome({status:"complete",prepared:true,buildIndex:blocks.length,pauseReason:""});setRuntime({currentAction:"idle",lastAction:"building",actionStartedTick:0,lastError:""});try{entity.triggerEvent("hiw:set_idle");}catch{}healWorker(entity);sound(entity.dimension,"ambient.cave",home.origin,0.5,1.0);try{player?.sendMessage("§2[Herobrine] Dom zostal ukonczony blok po bloku.");}catch{}info("build",`Dom ${home.variant} zakonczony.`);if(session.onReady)system.run(()=>session.onReady());}
function createBuildSession(entity,player,onReady){const home=state().home;const blueprint=getBlueprint(home.variant);const blocks=sortedBlocks(blueprint);const prepareColumns=[];for(let x=-(blueprint.radius+1);x<=blueprint.radius+1;x++)for(let z=-(blueprint.radius+1);z<=blueprint.radius+1;z++)prepareColumns.push({x,z});return{token:generation,entity,entityId:entity.id,player,onReady,home:{...home},blueprint,blocks,expected:expectedBlocks(blueprint,home.origin),index:Math.max(0,Math.min(home.buildIndex??0,blocks.length)),prepareColumns,prepareIndex:0,lastZone:"",zone:"",station:undefined,timer:undefined,stage:home.prepared?"blocks":"prepare"};}
function launchBuild(entity,player,onReady){if(!isValid(entity)||active)return false;const session=createBuildSession(entity,player,onReady);active=session;setHome({status:session.stage==="prepare"?"preparing":"building",pauseReason:""});setRuntime({currentAction:session.stage==="prepare"?"preparing_site":"building",actionStartedTick:system.currentTick,lastError:""});equip(entity,session.stage==="prepare"?"minecraft:iron_shovel":"minecraft:iron_axe");const firstZone=session.stage==="prepare"?"foundation":String(session.blocks[session.index]?.zone??"north");moveToStation(session,firstZone,()=>{if(active!==session)return;if(session.stage==="prepare")prepareOneColumn(session);else startNextBlock(session);});return true;}
export function ensureHome(entity,player,onReady){if(!isValid(entity)||active)return;const value=state();const dimensionId=entity.dimension.id;if(dimensionId!=="minecraft:overworld"&&dimensionId!=="overworld"){setHome({status:"paused",pauseReason:"Dom mozna budowac tylko w Overworldzie."});player?.sendMessage("§c[Herobrine] Budowanie domu dziala tylko w normalnym swiecie.");return;}if(value.home.status==="complete"&&value.home.origin){onReady?.();return;}if(value.home.status==="paused"){setRuntime({currentAction:"build_paused",actionStartedTick:0});return;}if(["preparing","building"].includes(value.home.status)&&value.home.origin){launchBuild(entity,player,onReady);return;}if(!value.settings.buildingEnabled||searchActive)return;searchActive=true;setHome({status:"searching",pauseReason:""});setRuntime({currentAction:"site_search",actionStartedTick:system.currentTick});findBuildingSite(entity,player,value.settings.houseVariant,site=>{searchActive=false;if(!site){setHome({status:"none",pauseReason:"Nie znaleziono miejsca automatycznie. Uzyj Zbuduj dom przede mna."});recordError("Brak automatycznego miejsca na dom. Uzyj polecenia w ksiazce.");player?.sendMessage("§e[Herobrine] Nie znalazlem miejsca automatycznie. Stan na otwartym terenie i wybierz Zbuduj dom przede mna.");return;}setHome({status:"building",dimension:entity.dimension.id,origin:site.origin,variant:value.settings.houseVariant,prepared:false,buildIndex:0,pauseReason:""});launchBuild(entity,player,onReady);});}
export function forceBuildAtPlayer(entity,player,onReady){if(!isValid(entity)||!player?.isValid)return false;const site=findSiteInFront(player,state().settings.houseVariant);if(!site){player.sendMessage("§c[Herobrine] Nie ma bezpiecznego miejsca przed toba. Wyjdz na otwarty teren i sprobuj ponownie.");return false;}cancelAllBuilds();resetHome();setHome({status:"building",dimension:player.dimension.id,origin:site.origin,variant:state().settings.houseVariant,prepared:false,buildIndex:0,pauseReason:""});player.sendMessage(`§7[Herobrine] Rozpoczyna powolna budowe przy ${site.origin.x} ${site.origin.y} ${site.origin.z}.`);return launchBuild(entity,player,onReady);}
export function resumeBuild(entity,player,onReady){if(state().home.status==="paused")setHome({status:"building",pauseReason:""});ensureHome(entity,player,onReady);}
export function cancelAllBuilds(){generation++;searchActive=false;if(active){clearTimer(active);cancelMovement(active.entity,"build_cancelled");try{active.entity.triggerEvent("hiw:set_idle");}catch{}equip(active.entity,undefined);}active=undefined;}
export function isBuilding(entity){if(!active)return false;return !entity||active.entityId===entity.id;}
export function buildSafetyAnchor(entity){if(!active||entity&&active.entityId!==entity.id)return;return{location:active.station??stationForZone(active.home.origin,"north",active.blueprint),facing:active.home.origin};}
export function rescueActiveBuilder(entity){return Boolean(active&&active.entityId===entity.id&&rescueToCurrentStation(active));}
