import { system } from "@minecraft/server";
import { BUILD } from "./config.js";
import { getBlueprint } from "./blueprints.js";
import { cancelMovement, goTo } from "./movement.js";
import { setRuntime, state } from "./storage.js";
import { blockAt, equip, isProtectedType, isReplaceableType, isValid, lookAt, play, sound } from "./utils.js";
import { setWorkerMode, teleportWorkerSafely } from "./worker_safety.js";
import { error } from "./logger.js";
let repairSession; let repairGeneration=0;
function buildDelay(){const pace=state().settings.buildPace??"normal";return BUILD.paceTicks[pace]??BUILD.paceTicks.normal;}
function absolute(origin,offset){return{x:origin.x+offset.x,y:origin.y+offset.y,z:origin.z+offset.z};}
function directSet(dimension,location,typeId){try{dimension.setBlockType({x:Math.floor(location.x),y:Math.floor(location.y),z:Math.floor(location.z)},typeId);return true;}catch{return false;}}
function clearTimer(session){if(session?.timer!==undefined){try{system.clearRun(session.timer);}catch{}session.timer=undefined;}}
function schedule(session,ticks,callback){clearTimer(session);session.timer=system.runTimeout(()=>{session.timer=undefined;if(repairSession!==session||session.token!==repairGeneration)return;callback();},Math.max(1,ticks));}
function finishRepair(session,success,message){if(repairSession!==session)return;clearTimer(session);repairSession=undefined;cancelMovement(session.entity,"repair_complete");equip(session.entity,undefined);try{session.entity.triggerEvent("hiw:set_idle");}catch{}setRuntime({currentAction:"idle",lastAction:"repair",actionStartedTick:0,lastError:success?"":message});try{session.player?.sendMessage(success?`§2[Herobrine] Naprawa zakonczona. Naprawiono ${session.fixed}, pominieto ${session.blocked}.`:`§c[Herobrine] Naprawa zatrzymana: ${message}`);}catch{}if(success&&session.onReady)system.run(()=>session.onReady());}
function nextRepair(session){if(!isValid(session.entity)){finishRepair(session,false,"Encja przestala istniec.");return;}if(session.index>=session.tasks.length){finishRepair(session,true,"");return;}const task=session.tasks[session.index++];try{const block=blockAt(session.entity.dimension,task.location);if(!block)throw new Error("Chunk domu nie jest zaladowany.");if(block.typeId===task.typeId){schedule(session,1,()=>nextRepair(session));return;}if(isProtectedType(block.typeId)&&!isReplaceableType(block.typeId)){session.blocked++;schedule(session,1,()=>nextRepair(session));return;}setWorkerMode(session.entity);lookAt(session.entity,task.location);play(session.entity,"animation.hiw.herobrine.attack");if(!directSet(session.entity.dimension,task.location,task.typeId))throw new Error(`Nie udalo sie postawic ${task.typeId}.`);sound(session.entity.dimension,task.sound,task.location,0.82,0.42);session.fixed++;try{session.player?.onScreenDisplay.setActionBar(`§8Naprawa domu: ${session.index}/${session.tasks.length}`);}catch{}schedule(session,buildDelay(),()=>nextRepair(session));}catch(e){error("repair",e);finishRepair(session,false,e instanceof Error?e.message:String(e));}}
export async function repairHome(entity,player,onReady){if(!isValid(entity)||repairSession)return false;const home=state().home;if(home.status!=="complete"||!home.origin){player?.sendMessage("§cNajpierw dom musi byc ukonczony.");return false;}const blueprint=getBlueprint(home.variant);const tasks=[];for(const entry of blueprint.blocks){const location=absolute(home.origin,entry.offset);const block=blockAt(entity.dimension,location);if(!block||block.typeId===entry.typeId)continue;tasks.push({location,typeId:entry.typeId,sound:entry.sound});}if(!tasks.length){player?.sendMessage("§2[Herobrine] Dom nie wymaga naprawy.");return true;}const station={x:home.origin.x+0.5,y:home.origin.y,z:home.origin.z-blueprint.radius-3};cancelMovement(entity,"repair_start");const moved=await goTo(entity,station,{speed:"walk",arrivalRadius:2.2});if(!moved.success&&!teleportWorkerSafely(entity,station,home.origin)){player?.sendMessage("§cNie znaleziono bezpiecznego stanowiska naprawy.");return false;}const session={token:repairGeneration,entity,player,onReady,tasks,index:0,fixed:0,blocked:0,timer:undefined};repairSession=session;setRuntime({currentAction:"repair",actionStartedTick:system.currentTick,lastError:""});equip(entity,"minecraft:iron_axe");setWorkerMode(entity);schedule(session,8,()=>nextRepair(session));return true;}
export function cancelRepair(entity){repairGeneration++;if(repairSession){clearTimer(repairSession);cancelMovement(repairSession.entity,"repair_cancelled");try{repairSession.entity.triggerEvent("hiw:set_idle");}catch{}equip(repairSession.entity,undefined);}repairSession=undefined;if(entity&&isValid(entity)){try{entity.triggerEvent("hiw:set_idle");}catch{}}}
export function isRepairing(entity){if(!repairSession)return false;return !entity||repairSession.entity.id===entity.id;}
export function inspectHome(entity){const home=state().home;if(!home.origin||home.status!=="complete")return{total:0,correct:0,missing:0,blocked:0};const blueprint=getBlueprint(home.variant);let correct=0,missing=0,blocked=0;for(const entry of blueprint.blocks){const block=blockAt(entity.dimension,absolute(home.origin,entry.offset));if(block?.typeId===entry.typeId)correct++;else if(block&&isProtectedType(block.typeId)&&!isReplaceableType(block.typeId))blocked++;else missing++;}return{total:blueprint.blocks.length,correct,missing,blocked};}
