import { system } from "@minecraft/server";
import { TUNNEL } from "./config.js";
import { getBlueprint } from "./blueprints.js";
import { cancelMovement } from "./movement.js";
import { recordError, setRuntime, setTunnel, state } from "./storage.js";
import { blockAt, equip, isProtectedType, isReplaceableType, isValid, lookAt, play, sound } from "./utils.js";
import { entityInsideBlocks, healWorker, setWorkerMode, teleportWorkerSafely } from "./worker_safety.js";
import { error } from "./logger.js";
function currentTunnelDelay(){const pace=state().settings.buildPace??"normal";return TUNNEL.paceTicks[pace]??TUNNEL.paceTicks.normal;}
let active;let generation=0;
function directSet(dimension,location,typeId){try{dimension.setBlockType({x:Math.floor(location.x),y:Math.floor(location.y),z:Math.floor(location.z)},typeId);return true;}catch{return false;}}
function clearTimer(session){if(session?.timer!==undefined){try{system.clearRun(session.timer);}catch{}session.timer=undefined;}}
function schedule(session,delay,callback){if(!session||active!==session)return;clearTimer(session);session.timer=system.runTimeout(()=>{session.timer=undefined;if(active!==session||session.token!==generation)return;callback();},Math.max(1,delay));}
function entranceFor(home,blueprint){return{x:home.origin.x+0.5,y:home.origin.y,z:home.origin.z+blueprint.radius+3};}
function addCarve(operations,x,y,z){operations.push({kind:"carve",location:{x,y,z},typeId:"minecraft:air",sound:"dig.stone"});}
function addPlace(operations,x,y,z,typeId,soundId="dig.stone"){operations.push({kind:"place",location:{x,y,z},typeId,sound:soundId});}
function makeOperations(home,blueprint,previousLength){const operations=[];const startZ=home.origin.z+blueprint.radius+1;const flatY=home.origin.y-TUNNEL.depth;if(previousLength===0){for(let step=0;step<=TUNNEL.stairLength;step++){const z=startZ+step;const floorY=home.origin.y-step;for(let xOffset=0;xOffset<=1;xOffset++){for(let yOffset=0;yOffset<=2;yOffset++)addCarve(operations,home.origin.x+xOffset,floorY+yOffset,z);addPlace(operations,home.origin.x+xOffset,floorY-1,z,"minecraft:cobbled_deepslate");}}}const extensionStart=startZ+TUNNEL.stairLength+1+previousLength;const extensionEnd=extensionStart+TUNNEL.extensionLength-1;for(let z=extensionStart;z<=extensionEnd;z++){for(let xOffset=0;xOffset<=1;xOffset++){for(let yOffset=0;yOffset<=2;yOffset++)addCarve(operations,home.origin.x+xOffset,flatY+yOffset,z);addPlace(operations,home.origin.x+xOffset,flatY-1,z,"minecraft:cobbled_deepslate");}if((z-extensionStart)%4===0){for(let y=flatY;y<=flatY+2;y++){addPlace(operations,home.origin.x-1,y,z,"minecraft:stripped_spruce_log","dig.wood");addPlace(operations,home.origin.x+2,y,z,"minecraft:stripped_spruce_log","dig.wood");}addPlace(operations,home.origin.x,flatY+3,z,"minecraft:spruce_planks","dig.wood");addPlace(operations,home.origin.x+1,flatY+3,z,"minecraft:spruce_planks","dig.wood");addPlace(operations,home.origin.x-1,flatY+1,z,"minecraft:redstone_torch","dig.wood");}}return operations;}
function stopSession(entity){if(active?.entityId===entity?.id){clearTimer(active);active=undefined;}cancelMovement(entity,"tunnel_finished");equip(entity,undefined);}
function pauseTunnel(session,message){stopSession(session.entity);try{session.entity.triggerEvent("hiw:set_idle");}catch{}setTunnel({status:"paused",pauseReason:message});setRuntime({currentAction:"tunnel_paused",actionStartedTick:0,lastError:message});recordError(message);try{session.player?.sendMessage(`§c[Herobrine] Tunel zatrzymany: ${message}`);}catch{}}
function rescueToEntrance(session){if(!session||!isValid(session.entity))return false;const rescued=teleportWorkerSafely(session.entity,session.entrance,session.operations[session.index]?.location??session.home.origin);if(rescued)setWorkerMode(session.entity);return rescued;}
function performOperation(session){if(!session||active!==session||!isValid(session.entity))return;if(session.index>=session.operations.length){completeTunnel(session);return;}const operation=session.operations[session.index];try{healWorker(session.entity);if(entityInsideBlocks(session.entity)&&!rescueToEntrance(session))throw new Error("Nie udalo sie wydostac Herobrine'a z bloku.");const block=blockAt(session.entity.dimension,operation.location);if(!block)throw new Error("Chunk tunelu nie jest zaladowany.");if(operation.kind==="carve"&&session.safeMode&&isProtectedType(block.typeId))throw new Error(`Tunel trafil na chroniony blok ${block.typeId}.`);if(operation.kind==="place"&&isProtectedType(block.typeId)&&block.typeId!==operation.typeId)throw new Error(`Chroniony blok pod tunelem: ${block.typeId}.`);setWorkerMode(session.entity);lookAt(session.entity,operation.location);play(session.entity,"animation.hiw.herobrine.attack");if(operation.kind==="carve"){if(block.typeId!=="minecraft:air"&&!directSet(session.entity.dimension,operation.location,"minecraft:air"))throw new Error("Nie udalo sie wykopac bloku.");}else if(block.typeId!==operation.typeId){if(block.typeId!=="minecraft:air"&&!isReplaceableType(block.typeId)&&!block.typeId.includes("stone")&&!block.typeId.includes("deepslate")&&!block.typeId.includes("dirt")&&!block.typeId.includes("gravel"))throw new Error(`Nie mozna postawic podpory w ${block.typeId}.`);if(!directSet(session.entity.dimension,operation.location,operation.typeId))throw new Error(`Nie udalo sie postawic ${operation.typeId}.`);}sound(session.entity.dimension,operation.sound,operation.location,0.8,0.38);session.index++;setTunnel({buildIndex:session.index});try{session.player?.onScreenDisplay.setActionBar(`§8Kopanie tunelu: ${session.index}/${session.operations.length}`);}catch{}schedule(session,currentTunnelDelay(),()=>performOperation(session));}catch(e){error("tunnel-operation",e);pauseTunnel(session,e instanceof Error?e.message:String(e));}}
function completeTunnel(session){if(!session||active!==session)return;const newLength=session.previousLength+TUNNEL.extensionLength;stopSession(session.entity);try{session.entity.triggerEvent("hiw:set_idle");}catch{}healWorker(session.entity);setTunnel({status:"complete",length:newLength,buildIndex:0,pauseReason:""});setRuntime({currentAction:"idle",lastAction:"tunnel",actionStartedTick:0,lastError:""});try{session.player?.sendMessage(`§2[Herobrine] Tunel ma teraz ${newLength} blokow dlugosci.`);}catch{}if(session.onReady)system.run(()=>session.onReady());}
export function startTunnel(entity,player,onReady){if(!isValid(entity)||active)return false;const data=state();const home=data.home;if(home.status!=="complete"||!home.origin){player?.sendMessage("§cNajpierw Herobrine musi ukonczyc dom.");return false;}const blueprint=getBlueprint(home.variant);const previousLength=data.tunnel.length??0;const operations=makeOperations(home,blueprint,previousLength);const entrance=entranceFor(home,blueprint);const session={token:generation,entity,entityId:entity.id,player,onReady,home,blueprint,safeMode:data.settings.safeMode,previousLength,operations,index:0,entrance,timer:undefined};active=session;cancelMovement(entity,"tunnel_start");equip(entity,"minecraft:iron_pickaxe");setTunnel({status:"building",buildIndex:0,pauseReason:""});setRuntime({currentAction:"tunnel",actionStartedTick:system.currentTick,lastError:""});if(!teleportWorkerSafely(entity,entrance,operations[0]?.location??home.origin)){pauseTunnel(session,"Nie znaleziono bezpiecznego wejscia do tunelu.");return false;}setWorkerMode(entity);player?.sendMessage("§7[Herobrine] Tunel bedzie kopany powoli, po jednym bloku.");schedule(session,10,()=>performOperation(session));return true;}
export function cancelTunnel(entity){generation++;if(active){clearTimer(active);cancelMovement(active.entity,"tunnel_cancelled");try{active.entity.triggerEvent("hiw:set_idle");}catch{}equip(active.entity,undefined);}active=undefined;if(entity&&isValid(entity)){try{entity.triggerEvent("hiw:set_idle");}catch{}equip(entity,undefined);}}
export function isTunneling(entity){if(!active)return false;return !entity||active.entityId===entity.id;}
export function tunnelSafetyAnchor(entity){if(!active||entity&&active.entityId!==entity.id)return;return{location:active.entrance,facing:active.operations[active.index]?.location??active.home.origin};}
export function rescueActiveTunneler(entity){return Boolean(active&&active.entityId===entity.id&&rescueToEntrance(active));}
